/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.wildpark.dswp.supports;

/**
 *
 * @author Panker-RDP
 */
public class MailTemplate {
    public static String lores="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et enim pretium, iaculis orci quis, lobortis lectus. Donec et dolor eget orci tincidunt pellentesque a vitae eros. Nulla viverra facilisis purus, eget facilisis tellus blandit in. Nulla lectus nisl, iaculis auctor placerat quis, fringilla ornare risus. In venenatis dui ut ornare aliquam. Fusce eu erat eget nibh ultrices tristique at in nibh. Ut id nunc nisl. Curabitur malesuada ultrices nunc ac pharetra. Proin a risus accumsan sapien varius placerat vitae quis nunc. Nulla bibendum mattis pulvinar. Ut vel nibh at leo rutrum ornare. Nam molestie sagittis urna, in vehicula leo volutpat quis. Praesent vitae sem id ex malesuada faucibus.\n" +
"\n" +
"Praesent lacinia elit quis blandit imperdiet. Nullam sed facilisis mi, ac convallis enim. Nam ut erat mollis, dictum nibh non, euismod orci. Pellentesque in ornare nibh. Proin semper, mi a faucibus facilisis, turpis nibh efficitur neque, sed posuere neque sem non dui. Sed ut dolor et lacus tristique ultricies. Proin dignissim libero sed neque ullamcorper faucibus. Nunc tincidunt tincidunt nibh sit amet euismod. Phasellus sit amet posuere augue. Nullam ligula erat, efficitur quis ante id, ornare aliquet tortor. Aenean eu auctor augue. Vestibulum lacinia libero libero, at malesuada lorem ornare ut. Mauris a est mi. Mauris malesuada mi ex, ut gravida eros gravida sit amet.\n" +
"\n" +
"Nam ac pulvinar diam. Aenean vulputate bibendum arcu a eleifend. Proin ornare laoreet tortor, nec lacinia neque sodales sit amet. Donec non ipsum eu mi hendrerit posuere sit amet aliquam massa. Donec dictum est et lacus dignissim, sit amet maximus tortor commodo. Ut malesuada euismod turpis convallis vulputate. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus ultrices eget lacus in iaculis.\n" +
"\n" +
"Aenean pellentesque accumsan tincidunt. Cras est dui, mollis sit amet mollis quis, pharetra at ipsum. Duis bibendum eget augue in pharetra. Morbi tincidunt quis augue eget sodales. Ut convallis eget odio vitae tincidunt. Mauris egestas lacus ipsum, nec dignissim ligula euismod a. Nunc interdum et justo at dictum. Sed id quam felis. Maecenas risus ex, tincidunt at arcu at, dapibus ultricies quam. Vivamus quis fringilla metus. Suspendisse potenti. Nam molestie mattis lectus, eget suscipit enim semper et. Duis efficitur ipsum eu nisi efficitur placerat. Fusce molestie fermentum quam, eget semper leo hendrerit a.\n" +
"\n" +
"Pellentesque scelerisque semper ex, vel rhoncus nisl. Suspendisse ac nisl libero. Vestibulum vitae pellentesque ante. Nunc eget faucibus ex. Quisque congue commodo est. Aenean nec congue urna. Integer id gravida leo. Morbi et ultrices tortor, sit amet condimentum eros. Morbi vehicula mi eget orci efficitur, non luctus mauris luctus. Ut enim arcu, sodales vel suscipit ut, suscipit tempus mauris.";
    public static String getHtml(String login, String password) {
        return "<html class=\"js html\" lang=\"ru-RU\">\n"
                + " <head>\n"
                + "\n"
                + "  \n"
                + "  <meta http-equiv=\"Content-type\" content=\"text/html;charset=UTF-8\"/>\n"
                + "  <meta name=\"generator\" content=\"2015.1.0.342\"/>\n"
                + "  <title>Dark Side Wild Park</title>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n"
                + "  <!-- CSS -->\n" 
                + getCss()
                + "  </head>\n"
                + " <body>\n"
                + "\n"
                + "  <div class=\"clearfix borderbox\" id=\"page\"><!-- group -->\n"
                + "   <div class=\"clearfix\" id=\"u905\"><!-- group -->\n"
                + "    <div class=\"clip_frame\" id=\"u906\"><!-- image -->\n"
                + "     <img class=\"block\" id=\"u906_img\" src=\"resources/images/empty_logo.png\" alt=\"\" data-image-width=\"113\" data-image-height=\"113\"/>\n"
                + "    </div>\n"
                + "    <img id=\"u908-4\" alt=\"Дикий Сад\" src=\"resources/images/u908-4.png\" data-image-width=\"246\"/><!-- rasterized frame -->\n"
                + "   </div>\n"
                + "   <p>Уважаемый "
                +login
                +", Ваша учетная запись еще не активирована. Ваш запрос на активацию скоро будет рассмотрен администрацией. Пароль для доступа к порталу после активации аккаунта - "
                +password
                +
                " . Убедительная просьба, смените пароль для большей безопасности после активации, и не сообщайте его никаким третьим лицам!</p><br/>\n"
                + "	<p>Информационное бюро Внутреннего Портала Дикого Сада</p>\n"
                + "   <div class=\"verticalspacer\"></div>\n"
                + "  </div>  \n"
                + "   </body>\n"
                + "</html>";
    }

    private static String getCss() {
        return "<style>\n"
                + "	#page\n"
                + "{\n"
                + "	z-index: 1;\n"
                + "	min-height: 257px;\n"
                + "	background-image: none;\n"
                + "	border-width: 0px;\n"
                + "	border-color: #000000;\n"
                + "	background-color: transparent;\n"
                + "	padding-bottom: 243px;\n"
                + "	width: 100%;\n"
                + "	max-width: 960px;\n"
                + "	margin-left: auto;\n"
                + "	margin-right: auto;\n"
                + "}\n"
                + "\n"
                + "#u905\n"
                + "{\n"
                + "	z-index: 2;\n"
                + "	border-width: 0px;\n"
                + "	border-color: transparent;\n"
                + "	background-color: transparent;\n"
                + "	padding-bottom: 143px;\n"
                + "	position: fixed;\n"
                + "	top: 9px;\n"
                + "	left: 60px;\n"
                + "	width: 25%;\n"
                + "	max-width: 240px;\n"
                + "}\n"
                + "\n"
                + "#u906\n"
                + "{\n"
                + "	z-index: 3;\n"
                + "	background-color: transparent;\n"
                + "	opacity: 0.25;\n"
                + "	-ms-filter: \"progid:DXImageTransform.Microsoft.Alpha(Opacity=25)\";\n"
                + "	filter: alpha(opacity=25);\n"
                + "	position: fixed;\n"
                + "	top: 9px;\n"
                + "	left: 124px;\n"
                + "	width: 11.78%;\n"
                + "	max-width: 113px;\n"
                + "}\n"
                + "\n"
                + "#u906_img\n"
                + "{\n"
                + "	width: 100%;\n"
                + "}\n"
                + "\n"
                + "#u908-4\n"
                + "{\n"
                + "	z-index: 5;\n"
                + "	display: block;\n"
                + "	vertical-align: top;\n"
                + "	position: fixed;\n"
                + "	top: 80px;\n"
                + "	left: 60px;\n"
                + "	width: 25.63%;\n"
                + "	max-width: 246px;\n"
                + "}\n"
                + "\n"
                + "#u918-10\n"
                + "{\n"
                + "	z-index: 9;\n"
                + "	display: block;\n"
                + "	vertical-align: top;\n"
                + "	position: relative;\n"
                + "	margin-right: -10000px;\n"
                + "	margin-top: 172px;\n"
                + "	width: 87.5%;\n"
                + "	margin-left: 6.25%;\n"
                + "	left: 0px;\n"
                + "}\n"
                + "\n"
                + "#muse_css_mq,.html\n"
                + "{\n"
                + "	background-color: #FFFFFF;\n"
                + "}\n"
                + "\n"
                + "body\n"
                + "{\n"
                + "	position: relative;\n"
                + "	min-width: 320px;\n"
                + "}\n"
                + "\n"
                + "html\n"
                + "{\n"
                + "	min-height: 100%;\n"
                + "	min-width: 100%;\n"
                + "	-ms-text-size-adjust: none;\n"
                + "}\n"
                + "\n"
                + "body,div,dl,dt,dd,ul,ol,li,nav,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,button,textarea,p,blockquote,th,td,a\n"
                + "{\n"
                + "	margin: 0px;\n"
                + "	padding: 0px;\n"
                + "	border-width: 0px;\n"
                + "	border-style: solid;\n"
                + "	border-color: transparent;\n"
                + "	-webkit-transform-origin: left top;\n"
                + "	-ms-transform-origin: left top;\n"
                + "	-o-transform-origin: left top;\n"
                + "	transform-origin: left top;\n"
                + "	background-repeat: no-repeat;\n"
                + "}\n"
                + "\n"
                + ".transition\n"
                + "{\n"
                + "	-webkit-transition-property: background-image,background-position,background-color,border-color,border-radius,color,font-size,font-style,font-weight,letter-spacing,line-height,text-align,box-shadow,text-shadow,opacity;\n"
                + "	transition-property: background-image,background-position,background-color,border-color,border-radius,color,font-size,font-style,font-weight,letter-spacing,line-height,text-align,box-shadow,text-shadow,opacity;\n"
                + "}\n"
                + "\n"
                + ".transition *\n"
                + "{\n"
                + "	-webkit-transition: inherit;\n"
                + "	transition: inherit;\n"
                + "}\n"
                + "\n"
                + "table\n"
                + "{\n"
                + "	border-collapse: collapse;\n"
                + "	border-spacing: 0px;\n"
                + "}\n"
                + "\n"
                + "fieldset,img\n"
                + "{\n"
                + "	border: 0px;\n"
                + "	border-style: solid;\n"
                + "	-webkit-transform-origin: left top;\n"
                + "	-ms-transform-origin: left top;\n"
                + "	-o-transform-origin: left top;\n"
                + "	transform-origin: left top;\n"
                + "}\n"
                + "\n"
                + "address,caption,cite,code,dfn,em,strong,th,var,optgroup\n"
                + "{\n"
                + "	font-style: inherit;\n"
                + "	font-weight: inherit;\n"
                + "}\n"
                + "\n"
                + "del,ins\n"
                + "{\n"
                + "	text-decoration: none;\n"
                + "}\n"
                + "\n"
                + "li\n"
                + "{\n"
                + "	list-style: none;\n"
                + "}\n"
                + "\n"
                + "caption,th\n"
                + "{\n"
                + "	text-align: left;\n"
                + "}\n"
                + "\n"
                + "h1,h2,h3,h4,h5,h6\n"
                + "{\n"
                + "	font-size: 100%;\n"
                + "	font-weight: inherit;\n"
                + "}\n"
                + "\n"
                + "input,button,textarea,select,optgroup,option\n"
                + "{\n"
                + "	font-family: inherit;\n"
                + "	font-size: inherit;\n"
                + "	font-style: inherit;\n"
                + "	font-weight: inherit;\n"
                + "}\n"
                + "\n"
                + "body\n"
                + "{\n"
                + "	font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\n"
                + "	text-align: left;\n"
                + "	font-size: 14px;\n"
                + "	line-height: 17px;\n"
                + "	word-wrap: break-word;\n"
                + "	text-rendering: optimizeLegibility;/* kerning, primarily */\n"
                + "	-moz-font-feature-settings: 'liga';\n"
                + "	-ms-font-feature-settings: 'liga';\n"
                + "	-webkit-font-feature-settings: 'liga';\n"
                + "	font-feature-settings: 'liga';\n"
                + "}\n"
                + "\n"
                + "a:link\n"
                + "{\n"
                + "	color: #0000FF;\n"
                + "	text-decoration: underline;\n"
                + "}\n"
                + "\n"
                + "a:visited\n"
                + "{\n"
                + "	color: #800080;\n"
                + "	text-decoration: underline;\n"
                + "}\n"
                + "\n"
                + "a:hover\n"
                + "{\n"
                + "	color: #0000FF;\n"
                + "	text-decoration: underline;\n"
                + "}\n"
                + "\n"
                + "a:active\n"
                + "{\n"
                + "	color: #EE0000;\n"
                + "	text-decoration: underline;\n"
                + "}\n"
                + "\n"
                + "a.nontext /* used to override default properties of 'a' tag */\n"
                + "{\n"
                + "	color: black;\n"
                + "	text-decoration: none;\n"
                + "	font-style: normal;\n"
                + "	font-weight: normal;\n"
                + "}\n"
                + "\n"
                + ".normal_text\n"
                + "{\n"
                + "	color: #000000;\n"
                + "	direction: ltr;\n"
                + "	font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\n"
                + "	font-size: 14px;\n"
                + "	font-style: normal;\n"
                + "	font-weight: normal;\n"
                + "	letter-spacing: 0px;\n"
                + "	line-height: 17px;\n"
                + "	text-align: left;\n"
                + "	text-decoration: none;\n"
                + "	text-indent: 0px;\n"
                + "	text-transform: none;\n"
                + "	vertical-align: 0px;\n"
                + "	padding: 0px;\n"
                + "}\n"
                + "\n"
                + ".list0 li:before\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	right: 100%;\n"
                + "	letter-spacing: 0px;\n"
                + "	text-decoration: none;\n"
                + "	font-weight: normal;\n"
                + "	font-style: normal;\n"
                + "}\n"
                + "\n"
                + ".rtl-list li:before\n"
                + "{\n"
                + "	right: auto;\n"
                + "	left: 100%;\n"
                + "}\n"
                + "\n"
                + ".nls-None > li:before,.nls-None .list3 > li:before,.nls-None .list6 > li:before\n"
                + "{\n"
                + "	margin-right: 6px;\n"
                + "	content: '•';\n"
                + "}\n"
                + "\n"
                + ".nls-None .list1 > li:before,.nls-None .list4 > li:before,.nls-None .list7 > li:before\n"
                + "{\n"
                + "	margin-right: 6px;\n"
                + "	content: '○';\n"
                + "}\n"
                + "\n"
                + ".nls-None,.nls-None .list1,.nls-None .list2,.nls-None .list3,.nls-None .list4,.nls-None .list5,.nls-None .list6,.nls-None .list7,.nls-None .list8\n"
                + "{\n"
                + "	padding-left: 34px;\n"
                + "}\n"
                + "\n"
                + ".nls-None.rtl-list,.nls-None .list1.rtl-list,.nls-None .list2.rtl-list,.nls-None .list3.rtl-list,.nls-None .list4.rtl-list,.nls-None .list5.rtl-list,.nls-None .list6.rtl-list,.nls-None .list7.rtl-list,.nls-None .list8.rtl-list\n"
                + "{\n"
                + "	padding-left: 0px;\n"
                + "	padding-right: 34px;\n"
                + "}\n"
                + "\n"
                + ".nls-None .list2 > li:before,.nls-None .list5 > li:before,.nls-None .list8 > li:before\n"
                + "{\n"
                + "	margin-right: 6px;\n"
                + "	content: '-';\n"
                + "}\n"
                + "\n"
                + ".nls-None.rtl-list > li:before,.nls-None .list1.rtl-list > li:before,.nls-None .list2.rtl-list > li:before,.nls-None .list3.rtl-list > li:before,.nls-None .list4.rtl-list > li:before,.nls-None .list5.rtl-list > li:before,.nls-None .list6.rtl-list > li:before,.nls-None .list7.rtl-list > li:before,.nls-None .list8.rtl-list > li:before\n"
                + "{\n"
                + "	margin-right: 0px;\n"
                + "	margin-left: 6px;\n"
                + "}\n"
                + "\n"
                + ".TabbedPanelsTab\n"
                + "{\n"
                + "	white-space: nowrap;\n"
                + "}\n"
                + "\n"
                + ".MenuBar .MenuBarView,.MenuBar .SubMenuView /* Resets for ul and li in menus */\n"
                + "{\n"
                + "	display: block;\n"
                + "	list-style: none;\n"
                + "}\n"
                + "\n"
                + ".MenuBar .SubMenu\n"
                + "{\n"
                + "	display: none;\n"
                + "	position: absolute;\n"
                + "}\n"
                + "\n"
                + ".NoWrap\n"
                + "{\n"
                + "	white-space: nowrap;\n"
                + "	word-wrap: normal;\n"
                + "}\n"
                + "\n"
                + ".rootelem /* the root of the artwork tree */\n"
                + "{\n"
                + "	margin-left: auto;\n"
                + "	margin-right: auto;\n"
                + "}\n"
                + "\n"
                + ".colelem /* a child element of a column */\n"
                + "{\n"
                + "	display: inline;\n"
                + "	float: left;\n"
                + "	clear: both;\n"
                + "}\n"
                + "\n"
                + ".clearfix:after /* force a container to fit around floated items */\n"
                + "{\n"
                + "	content: \"\\0020\";\n"
                + "	visibility: hidden;\n"
                + "	display: block;\n"
                + "	height: 0px;\n"
                + "	clear: both;\n"
                + "}\n"
                + "\n"
                + "*:first-child+html .clearfix /* IE7 */\n"
                + "{\n"
                + "	zoom: 1;\n"
                + "}\n"
                + "\n"
                + ".clip_frame /* used to clip the contents as in the case of an image frame */\n"
                + "{\n"
                + "	overflow: hidden;\n"
                + "}\n"
                + "\n"
                + ".popup_anchor /* anchors an abspos popup */\n"
                + "{\n"
                + "	position: relative;\n"
                + "	width: 0px;\n"
                + "	height: 0px;\n"
                + "}\n"
                + "\n"
                + ".popup_element\n"
                + "{\n"
                + "	z-index: 100000;\n"
                + "}\n"
                + "\n"
                + ".svg\n"
                + "{\n"
                + "	display: block;\n"
                + "	vertical-align: top;\n"
                + "}\n"
                + "\n"
                + "span.wrap /* used to force wrap after floated array when nested inside a paragraph */\n"
                + "{\n"
                + "	content: '';\n"
                + "	clear: left;\n"
                + "	display: block;\n"
                + "}\n"
                + "\n"
                + "span.actAsInlineDiv /* used to simulate a DIV with inline display when already nested inside a paragraph */\n"
                + "{\n"
                + "	display: inline-block;\n"
                + "}\n"
                + "\n"
                + ".position_content,.excludeFromNormalFlow /* used when child content is larger than parent */\n"
                + "{\n"
                + "	float: left;\n"
                + "}\n"
                + "\n"
                + ".preload_images /* used to preload images used in non-default states */\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	overflow: hidden;\n"
                + "	left: -9999px;\n"
                + "	top: -9999px;\n"
                + "	height: 1px;\n"
                + "	width: 1px;\n"
                + "}\n"
                + "\n"
                + ".preload /* used to specifiy the dimension of preload item */\n"
                + "{\n"
                + "	height: 1px;\n"
                + "	width: 1px;\n"
                + "}\n"
                + "\n"
                + ".animateStates\n"
                + "{\n"
                + "	-webkit-transition: 0.3s ease-in-out;\n"
                + "	-moz-transition: 0.3s ease-in-out;\n"
                + "	-o-transition: 0.3s ease-in-out;\n"
                + "	transition: 0.3s ease-in-out;\n"
                + "}\n"
                + "\n"
                + "[data-whatinput=\"mouse\"] *:focus,[data-whatinput=\"touch\"] *:focus,input:focus,textarea:focus\n"
                + "{\n"
                + "	outline: none;\n"
                + "}\n"
                + "\n"
                + "textarea\n"
                + "{\n"
                + "	resize: none;\n"
                + "	overflow: auto;\n"
                + "}\n"
                + "\n"
                + ".fld-prompt /* form placeholders cursor behavior */\n"
                + "{\n"
                + "	pointer-events: none;\n"
                + "}\n"
                + "\n"
                + ".wrapped-input /* form inputs & placeholders let div styling show thru */\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	top: 0px;\n"
                + "	left: 0px;\n"
                + "	background: transparent;\n"
                + "	border: none;\n"
                + "}\n"
                + "\n"
                + ".submit-btn /* form submit buttons on top of sibling elements */\n"
                + "{\n"
                + "	z-index: 50000;\n"
                + "	cursor: pointer;\n"
                + "}\n"
                + "\n"
                + ".anchor_item /* used to specify anchor properties */\n"
                + "{\n"
                + "	width: 22px;\n"
                + "	height: 18px;\n"
                + "}\n"
                + "\n"
                + ".MenuBar .SubMenuVisible,.MenuBarVertical .SubMenuVisible,.MenuBar .SubMenu .SubMenuVisible,.popup_element.Active,span.actAsPara,.actAsDiv,a.nonblock.nontext,img.block\n"
                + "{\n"
                + "	display: block;\n"
                + "}\n"
                + "\n"
                + ".ose_ei\n"
                + "{\n"
                + "	visibility: hidden;\n"
                + "	z-index: 0;\n"
                + "}\n"
                + "\n"
                + ".widget_invisible,.js .invi,.js .mse_pre_init,.js .an_invi /* used to hide the widget before loaded */\n"
                + "{\n"
                + "	visibility: hidden;\n"
                + "}\n"
                + "\n"
                + ".no_vert_scroll\n"
                + "{\n"
                + "	overflow-y: hidden;\n"
                + "}\n"
                + "\n"
                + ".always_vert_scroll\n"
                + "{\n"
                + "	overflow-y: scroll;\n"
                + "}\n"
                + "\n"
                + ".always_horz_scroll\n"
                + "{\n"
                + "	overflow-x: scroll;\n"
                + "}\n"
                + "\n"
                + ".fullscreen\n"
                + "{\n"
                + "	overflow: hidden;\n"
                + "	left: 0px;\n"
                + "	top: 0px;\n"
                + "	position: fixed;\n"
                + "	height: 100%;\n"
                + "	width: 100%;\n"
                + "	-moz-box-sizing: border-box;\n"
                + "	-webkit-box-sizing: border-box;\n"
                + "	-ms-box-sizing: border-box;\n"
                + "	box-sizing: border-box;\n"
                + "}\n"
                + "\n"
                + ".fullwidth\n"
                + "{\n"
                + "	position: absolute;\n"
                + "}\n"
                + "\n"
                + ".borderbox\n"
                + "{\n"
                + "	-moz-box-sizing: border-box;\n"
                + "	-webkit-box-sizing: border-box;\n"
                + "	-ms-box-sizing: border-box;\n"
                + "	box-sizing: border-box;\n"
                + "}\n"
                + "\n"
                + ".scroll_wrapper\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	overflow: auto;\n"
                + "	left: 0px;\n"
                + "	right: 0px;\n"
                + "	top: 0px;\n"
                + "	bottom: 0px;\n"
                + "	padding-top: 0px;\n"
                + "	padding-bottom: 0px;\n"
                + "	margin-top: 0px;\n"
                + "	margin-bottom: 0px;\n"
                + "}\n"
                + "\n"
                + ".browser_width > *\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	left: 0px;\n"
                + "	right: 0px;\n"
                + "}\n"
                + "\n"
                + ".list0 li,.MenuBar .MenuItemContainer,.SlideShowContentPanel .fullscreen img\n"
                + "{\n"
                + "	position: relative;\n"
                + "}\n"
                + "\n"
                + ".grpelem,.accordion_wrapper /* a child element of a group */\n"
                + "{\n"
                + "	display: inline;\n"
                + "	float: left;\n"
                + "}\n"
                + "\n"
                + ".fld-checkbox input[type=checkbox],.fld-radiobutton input[type=radio] /* Hide native checkbox */\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	overflow: hidden;\n"
                + "	clip: rect(0px, 0px, 0px, 0px);\n"
                + "	height: 1px;\n"
                + "	width: 1px;\n"
                + "	margin: -1px;\n"
                + "	padding: 0px;\n"
                + "	border: 0px;\n"
                + "}\n"
                + "\n"
                + ".fld-checkbox input[type=checkbox] + label,.fld-radiobutton input[type=radio] + label\n"
                + "{\n"
                + "	display: inline-block;\n"
                + "	background-repeat: no-repeat;\n"
                + "	cursor: pointer;\n"
                + "	float: left;\n"
                + "	width: 100%;\n"
                + "	height: 100%;\n"
                + "}\n"
                + "\n"
                + ".pointer_cursor,.fld-recaptcha-mode,.fld-recaptcha-refresh,.fld-recaptcha-help\n"
                + "{\n"
                + "	cursor: pointer;\n"
                + "}\n"
                + "\n"
                + "p,h1,h2,h3,h4,h5,h6,ol,ul,span.actAsPara /* disable Android font boosting */\n"
                + "{\n"
                + "	max-height: 1000000px;\n"
                + "}\n"
                + "\n"
                + ".superscript\n"
                + "{\n"
                + "	vertical-align: super;\n"
                + "	font-size: 66%;\n"
                + "	line-height: 0px;\n"
                + "}\n"
                + "\n"
                + ".subscript\n"
                + "{\n"
                + "	vertical-align: sub;\n"
                + "	font-size: 66%;\n"
                + "	line-height: 0px;\n"
                + "}\n"
                + "\n"
                + ".horizontalSlideShow /* disable left-right panning on horizondal slide shows */\n"
                + "{\n"
                + "	-ms-touch-action: pan-y;\n"
                + "	touch-action: pan-y;\n"
                + "}\n"
                + "\n"
                + ".verticalSlideShow /* disable up-down panning on vertical slide shows */\n"
                + "{\n"
                + "	-ms-touch-action: pan-x;\n"
                + "	touch-action: pan-x;\n"
                + "}\n"
                + "\n"
                + ".colelem100,.verticalspacer /* a child element of a column that is 100% width */\n"
                + "{\n"
                + "	clear: both;\n"
                + "}\n"
                + "\n"
                + ".popup_element.Inactive,.js .disn,.hidden,.breakpoint\n"
                + "{\n"
                + "	display: none;\n"
                + "}\n"
                + "\n"
                + "#muse_css_mq\n"
                + "{\n"
                + "	position: absolute;\n"
                + "	display: none;\n"
                + "	background-color: #FFFFFE;\n"
                + "}\n"
                + "\n"
                + ".fluid_height_spacer\n"
                + "{\n"
                + "	position: static;\n"
                + "	width: 0.01px;\n"
                + "	float: left;\n"
                + "}\n"
                + "\n"
                + "@media screen and (-webkit-min-device-pixel-ratio:0)\n"
                + "{\n"
                + "	body\n"
                + "	{\n"
                + "		text-rendering: auto;\n"
                + "	}\n"
                + "}\n"
                + "\n"
                + "  </style>\n"
                + "  ";
    }
}
